apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: primer-api
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: primer-api
    spec:
      containers:
        - image: fighterhayabusa/primer-api:minikube
          imagePullPolicy: Always
          name: primer-api
          ports:
            - containerPort: 8080
