apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: primer-webui-green
spec:
  replicas: 4
  template:
    metadata:
      name: primer-webui
      labels:
        app: primer-webui
        version: "0.1.1"
        env: prod
    spec:
      containers:
        - image: fighterhayabusa/primer-webui:green
          imagePullPolicy: Always
          name: primer-webui
          ports:
            - containerPort: 80
