apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: primer-webui-canary
spec:
  replicas: 2
  template:
    metadata:
      name: primer-webui
      labels:
        app: primer-webui
        version: "0.1"
        env: canary
    spec:
      containers:
        - image: fighterhayabusa/primer-webui:canary
          imagePullPolicy: Always
          name: primer-webui
          ports:
            - containerPort: 80
