apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: primer-api-prod
spec:
  replicas: 2
  template:
    metadata:
      name: primer-api
      labels:
        app: primer-api
        env: prod
    spec:
      containers:
        - image: fighterhayabusa/primer-api:bbl
          imagePullPolicy: Always
          name: primer-api
          ports:
            - containerPort: 8080
